"""invoice line frecency

Revision ID: 72d7bd86c2e7
Revises: dc0ec166d2ae
Create Date: 2026-08-19 14:33:16.132986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d7bd86c2e7'
down_revision: Union[str, Sequence[str], None] = 'dc0ec166d2ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default on last_used_at is required, not cosmetic: without it the
    # table rebuild fails NOT NULL for rows that already exist.
    with op.batch_alter_table('invoice_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_count', sa.Integer(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_lines', schema=None) as batch_op:
        batch_op.drop_column('last_used_at')
        batch_op.drop_column('use_count')

    # ### end Alembic commands ###
