"""initial schema

Revision ID: dc0ec166d2ae
Revises: 
Create Date: 2026-07-30 19:53:33.745752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc0ec166d2ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('sha256', name=op.f('pk_assets'))
    )
    op.create_table('countries',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_countries'))
    )
    op.create_table('currencies',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('decimal_places', sa.Integer(), nullable=False),
    sa.Column('decimal_separator', sa.String(length=1), nullable=False),
    sa.Column('grouping_separator', sa.String(length=1), nullable=False),
    sa.Column('symbol_position', sa.Enum('PREFIX', 'SUFFIX', name='moneysymbolposition'), nullable=False),
    sa.Column('symbol_spacing', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_currencies'))
    )
    op.create_table('document_type_registry',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('system', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_document_type_registry'))
    )
    op.create_table('languages',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('code_alpha_2', sa.String(length=2), nullable=False),
    sa.Column('label_en', sa.String(length=25), nullable=False),
    sa.Column('label_uk', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_languages'))
    )
    op.create_table('measurement_unit_registry',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('system', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_measurement_unit_registry'))
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_table('placeholder_registry',
    sa.Column('key', sa.String(length=90), nullable=False),
    sa.Column('system', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('type', sa.Enum('SCALAR', 'TABLE', 'COLUMN', name='placeholdertype'), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_placeholder_registry'))
    )
    op.create_table('representatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_representatives'))
    )
    op.create_table('snap_organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=18), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snap_organizations'))
    )
    op.create_table('snap_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snap_templates'))
    )
    op.create_table('tax_id_system_registry',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('system', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_tax_id_system_registry'))
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('system', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates')),
    sa.UniqueConstraint('code', name=op.f('uq_templates_code'))
    )
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=False),
    sa.Column('swift', sa.String(length=11), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], name=op.f('fk_bank_accounts_country_code_countries')),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], name=op.f('fk_bank_accounts_currency_code_currencies')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_bank_accounts_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_accounts')),
    sa.UniqueConstraint('iban', name=op.f('uq_bank_accounts_iban'))
    )
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.create_index('idx_organization_id', ['organization_id'], unique=False)

    op.create_table('country_localizations',
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], name=op.f('fk_country_localizations_country_code_countries')),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], name=op.f('fk_country_localizations_language_code_languages')),
    sa.PrimaryKeyConstraint('country_code', 'language_code', name=op.f('pk_country_localizations'))
    )
    op.create_table('currency_localizations',
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=90), nullable=False),
    sa.Column('symbol', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], name=op.f('fk_currency_localizations_currency_code_currencies')),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], name=op.f('fk_currency_localizations_language_code_languages')),
    sa.PrimaryKeyConstraint('currency_code', 'language_code', name=op.f('pk_currency_localizations'))
    )
    op.create_table('default_template_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_language_code', sa.String(length=3), nullable=False),
    sa.Column('secondary_language_code', sa.String(length=3), nullable=True),
    sa.Column('document_type_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('append_currency', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_type_code'], ['document_type_registry.code'], name=op.f('fk_default_template_config_document_type_code_document_type_registry')),
    sa.ForeignKeyConstraint(['primary_language_code'], ['languages.code'], name=op.f('fk_default_template_config_primary_language_code_languages')),
    sa.ForeignKeyConstraint(['secondary_language_code'], ['languages.code'], name=op.f('fk_default_template_config_secondary_language_code_languages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_default_template_config'))
    )
    op.create_table('document_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type_code', sa.String(length=30), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(length=32), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.Column('padding', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_type_code'], ['document_type_registry.code'], name=op.f('fk_document_sequences_document_type_code_document_type_registry')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_document_sequences_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_sequences')),
    sa.UniqueConstraint('organization_id', 'document_type_code', 'prefix', name='unique_organization_id_document_type_prefix')
    )
    op.create_table('document_type_registry_localizations',
    sa.Column('document_type_code', sa.String(length=30), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['document_type_code'], ['document_type_registry.code'], name=op.f('fk_document_type_registry_localizations_document_type_code_document_type_registry')),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], name=op.f('fk_document_type_registry_localizations_language_code_languages')),
    sa.PrimaryKeyConstraint('document_type_code', 'language_code', name=op.f('pk_document_type_registry_localizations'))
    )
    op.create_table('invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('measurement_unit_code', sa.String(length=30), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.ForeignKeyConstraint(['measurement_unit_code'], ['measurement_unit_registry.code'], name=op.f('fk_invoice_lines_measurement_unit_code_measurement_unit_registry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_lines'))
    )
    op.create_table('measurement_unit_registry_localizations',
    sa.Column('measurement_unit_code', sa.String(length=30), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], name=op.f('fk_measurement_unit_registry_localizations_language_code_languages')),
    sa.ForeignKeyConstraint(['measurement_unit_code'], ['measurement_unit_registry.code'], name=op.f('fk_measurement_unit_registry_localizations_measurement_unit_code_measurement_unit_registry')),
    sa.PrimaryKeyConstraint('measurement_unit_code', 'language_code', name=op.f('pk_measurement_unit_registry_localizations'))
    )
    op.create_table('organization_localizations',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('org_type', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], name=op.f('fk_organization_localizations_language_code_languages')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_localizations_organization_id_organizations')),
    sa.PrimaryKeyConstraint('organization_id', 'language_code', name=op.f('pk_organization_localizations'))
    )
    op.create_table('organization_representative_association',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('representative_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_representative_association_organization_id_organizations')),
    sa.ForeignKeyConstraint(['representative_id'], ['representatives.id'], name=op.f('fk_organization_representative_association_representative_id_representatives')),
    sa.PrimaryKeyConstraint('organization_id', 'representative_id', name=op.f('pk_organization_representative_association'))
    )
    op.create_table('placeholder_registry_localizations',
    sa.Column('placeholder_key', sa.String(length=90), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], name=op.f('fk_placeholder_registry_localizations_language_code_languages')),
    sa.ForeignKeyConstraint(['placeholder_key'], ['placeholder_registry.key'], name=op.f('fk_placeholder_registry_localizations_placeholder_key_placeholder_registry')),
    sa.PrimaryKeyConstraint('placeholder_key', 'language_code', name=op.f('pk_placeholder_registry_localizations'))
    )
    op.create_table('representative_localizations',
    sa.Column('representative_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], name=op.f('fk_representative_localizations_language_code_languages')),
    sa.ForeignKeyConstraint(['representative_id'], ['representatives.id'], name=op.f('fk_representative_localizations_representative_id_representatives')),
    sa.PrimaryKeyConstraint('representative_id', 'language_code', name=op.f('pk_representative_localizations'))
    )
    op.create_table('snap_bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=False),
    sa.Column('swift', sa.String(length=11), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], name=op.f('fk_snap_bank_accounts_currency_code_currencies')),
    sa.ForeignKeyConstraint(['organization_id'], ['snap_organizations.id'], name=op.f('fk_snap_bank_accounts_organization_id_snap_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snap_bank_accounts'))
    )
    op.create_table('snap_organization_localizations',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], name=op.f('fk_snap_organization_localizations_language_code_languages')),
    sa.ForeignKeyConstraint(['organization_id'], ['snap_organizations.id'], name=op.f('fk_snap_organization_localizations_organization_id_snap_organizations')),
    sa.PrimaryKeyConstraint('organization_id', 'language_code', name=op.f('pk_snap_organization_localizations'))
    )
    op.create_table('snap_representatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['snap_organizations.id'], name=op.f('fk_snap_representatives_organization_id_snap_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snap_representatives'))
    )
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(length=25), nullable=False),
    sa.Column('document_type_code', sa.String(length=30), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('primary_language_code', sa.String(length=3), nullable=False),
    sa.Column('secondary_language_code', sa.String(length=3), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['snap_organizations.id'], name=op.f('fk_snapshots_client_id_snap_organizations')),
    sa.ForeignKeyConstraint(['contractor_id'], ['snap_organizations.id'], name=op.f('fk_snapshots_contractor_id_snap_organizations')),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], name=op.f('fk_snapshots_currency_code_currencies')),
    sa.ForeignKeyConstraint(['document_type_code'], ['document_type_registry.code'], name=op.f('fk_snapshots_document_type_code_document_type_registry')),
    sa.ForeignKeyConstraint(['primary_language_code'], ['languages.code'], name=op.f('fk_snapshots_primary_language_code_languages')),
    sa.ForeignKeyConstraint(['secondary_language_code'], ['languages.code'], name=op.f('fk_snapshots_secondary_language_code_languages')),
    sa.ForeignKeyConstraint(['template_id'], ['snap_templates.id'], name=op.f('fk_snapshots_template_id_snap_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snapshots'))
    )
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_issue_date_serial_document_type', ['issue_date', 'serial', 'document_type_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshots_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshots_issue_date'), ['issue_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshots_serial'), ['serial'], unique=True)

    op.create_table('tax_id_system_registry_localizations',
    sa.Column('tax_id_system_code', sa.String(length=30), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], name=op.f('fk_tax_id_system_registry_localizations_language_code_languages')),
    sa.ForeignKeyConstraint(['tax_id_system_code'], ['tax_id_system_registry.code'], name=op.f('fk_tax_id_system_registry_localizations_tax_id_system_code_tax_id_system_registry')),
    sa.PrimaryKeyConstraint('tax_id_system_code', 'language_code', name=op.f('pk_tax_id_system_registry_localizations'))
    )
    op.create_table('tax_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('tax_id_system_code', sa.String(length=30), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('value', sa.String(length=17), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], name=op.f('fk_tax_ids_country_code_countries')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_tax_ids_organization_id_organizations')),
    sa.ForeignKeyConstraint(['tax_id_system_code'], ['tax_id_system_registry.code'], name=op.f('fk_tax_ids_tax_id_system_code_tax_id_system_registry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tax_ids')),
    sa.UniqueConstraint('organization_id', 'country_code', 'tax_id_system_code', name='unique_organization_tax_id_system')
    )
    with op.batch_alter_table('tax_ids', schema=None) as batch_op:
        batch_op.create_index('idx_country_system_value', ['country_code', 'tax_id_system_code', 'value'], unique=False)

    op.create_table('template_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('placeholders', sa.JSON(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name=op.f('fk_template_versions_template_id_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_versions')),
    sa.UniqueConstraint('template_id', 'version', name='unique_template_version')
    )
    op.create_table('bank_account_localizations',
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('bank_info', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], name=op.f('fk_bank_account_localizations_bank_account_id_bank_accounts')),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], name=op.f('fk_bank_account_localizations_language_code_languages')),
    sa.PrimaryKeyConstraint('bank_account_id', 'language_code', name=op.f('pk_bank_account_localizations'))
    )
    op.create_table('invoice_line_localizations',
    sa.Column('invoice_line_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['invoice_line_id'], ['invoice_lines.id'], name=op.f('fk_invoice_line_localizations_invoice_line_id_invoice_lines')),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], name=op.f('fk_invoice_line_localizations_language_code_languages')),
    sa.PrimaryKeyConstraint('invoice_line_id', 'language_code', name=op.f('pk_invoice_line_localizations'))
    )
    op.create_table('snap_bank_account_localizations',
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('bank_name', sa.String(length=120), nullable=False),
    sa.Column('bank_info', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_id'], ['snap_bank_accounts.id'], name=op.f('fk_snap_bank_account_localizations_bank_account_id_snap_bank_accounts')),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], name=op.f('fk_snap_bank_account_localizations_language_code_languages')),
    sa.PrimaryKeyConstraint('bank_account_id', 'language_code', name=op.f('pk_snap_bank_account_localizations'))
    )
    op.create_table('snap_invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('measurement_unit_code', sa.String(length=30), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['measurement_unit_code'], ['measurement_unit_registry.code'], name=op.f('fk_snap_invoice_lines_measurement_unit_code_measurement_unit_registry')),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], name=op.f('fk_snap_invoice_lines_snapshot_id_snapshots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snap_invoice_lines'))
    )
    op.create_table('snap_representative_localizations',
    sa.Column('representative_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], name=op.f('fk_snap_representative_localizations_language_code_languages')),
    sa.ForeignKeyConstraint(['representative_id'], ['snap_representatives.id'], name=op.f('fk_snap_representative_localizations_representative_id_snap_representatives')),
    sa.PrimaryKeyConstraint('representative_id', 'language_code', name=op.f('pk_snap_representative_localizations'))
    )
    op.create_table('template_version_assets',
    sa.Column('template_version_id', sa.Integer(), nullable=False),
    sa.Column('asset_sha256', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['asset_sha256'], ['assets.sha256'], name=op.f('fk_template_version_assets_asset_sha256_assets')),
    sa.ForeignKeyConstraint(['template_version_id'], ['template_versions.id'], name=op.f('fk_template_version_assets_template_version_id_template_versions')),
    sa.PrimaryKeyConstraint('template_version_id', 'asset_sha256', name=op.f('pk_template_version_assets'))
    )
    op.create_table('snap_invoice_line_localizations',
    sa.Column('invoice_line_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['invoice_line_id'], ['snap_invoice_lines.id'], name=op.f('fk_snap_invoice_line_localizations_invoice_line_id_snap_invoice_lines')),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], name=op.f('fk_snap_invoice_line_localizations_language_code_languages')),
    sa.PrimaryKeyConstraint('invoice_line_id', 'language_code', name=op.f('pk_snap_invoice_line_localizations'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snap_invoice_line_localizations')
    op.drop_table('template_version_assets')
    op.drop_table('snap_representative_localizations')
    op.drop_table('snap_invoice_lines')
    op.drop_table('snap_bank_account_localizations')
    op.drop_table('invoice_line_localizations')
    op.drop_table('bank_account_localizations')
    op.drop_table('template_versions')
    with op.batch_alter_table('tax_ids', schema=None) as batch_op:
        batch_op.drop_index('idx_country_system_value')

    op.drop_table('tax_ids')
    op.drop_table('tax_id_system_registry_localizations')
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshots_serial'))
        batch_op.drop_index(batch_op.f('ix_snapshots_issue_date'))
        batch_op.drop_index(batch_op.f('ix_snapshots_created_at'))
        batch_op.drop_index('idx_issue_date_serial_document_type')

    op.drop_table('snapshots')
    op.drop_table('snap_representatives')
    op.drop_table('snap_organization_localizations')
    op.drop_table('snap_bank_accounts')
    op.drop_table('representative_localizations')
    op.drop_table('placeholder_registry_localizations')
    op.drop_table('organization_representative_association')
    op.drop_table('organization_localizations')
    op.drop_table('measurement_unit_registry_localizations')
    op.drop_table('invoice_lines')
    op.drop_table('document_type_registry_localizations')
    op.drop_table('document_sequences')
    op.drop_table('default_template_config')
    op.drop_table('currency_localizations')
    op.drop_table('country_localizations')
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_index('idx_organization_id')

    op.drop_table('bank_accounts')
    op.drop_table('templates')
    op.drop_table('tax_id_system_registry')
    op.drop_table('snap_templates')
    op.drop_table('snap_organizations')
    op.drop_table('representatives')
    op.drop_table('placeholder_registry')
    op.drop_table('organizations')
    op.drop_table('measurement_unit_registry')
    op.drop_table('languages')
    op.drop_table('document_type_registry')
    op.drop_table('currencies')
    op.drop_table('countries')
    op.drop_table('assets')
    # ### end Alembic commands ###
